In [1]:
import pandas as pd
import numpy as np
import datetime
from tqdm import tqdm
import re
pd.options.display.max_rows = 4000
pd.options.display.max_columns = 40

In [2]:
## sales data for 2017 and 2018, mortgage data dduring those same time periods
sales_17 = pd.read_csv("nyc-rolling-sales.csv")
sales_18 = pd.read_csv('rollingsales_2018.csv')
mortgage15 = pd.read_csv("MORTGAGE15US.csv")
mortgage30 = pd.read_csv("MORTGAGE30US.csv")

/Users/Nicole/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# concat sales data
sales = sales_17.append(sales_18,ignore_index=True)
sales.head()

,ADDRESS,APARTMENT NUMBER,BLOCK,BOROUGH,BUILDING CLASS AT PRESENT,BUILDING CLASS AT TIME OF SALE,BUILDING CLASS CATEGORY,COMMERCIAL UNITS,EASE-MENT,GROSS SQUARE FEET,LAND SQUARE FEET,LOT,NEIGHBORHOOD,RESIDENTIAL UNITS,SALE DATE,SALE PRICE,TAX CLASS AT PRESENT,TAX CLASS AT TIME OF SALE,TOTAL UNITS,Unnamed: 0,YEAR BUILT,ZIP CODE
0,153 AVENUE B,,392,1,C2,C2,07 RENTALS - WALKUP APARTMENTS,0.0,,6440,1633,6,ALPHABET CITY,5.0,2017-07-19 00:00:00,6625000,2A,2,5,4.0,1900.0,10009.0
1,234 EAST 4TH STREET,,399,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,3.0,,18690,4616,26,ALPHABET CITY,28.0,2016-12-14 00:00:00,-,2,2,31,5.0,1900.0,10009.0
2,197 EAST 3RD STREET,,399,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,1.0,,7803,2212,39,ALPHABET CITY,16.0,2016-12-09 00:00:00,-,2,2,17,6.0,1900.0,10009.0
3,154 EAST 7TH STREET,,402,1,C4,C4,07 RENTALS - WALKUP APARTMENTS,0.0,,6794,2272,21,ALPHABET CITY,10.0,2016-09-23 00:00:00,3936272,2B,2,10,7.0,1913.0,10009.0
4,301 EAST 10TH STREET,,404,1,C2,C2,07 RENTALS - WALKUP APARTMENTS,0.0,,4615,2369,55,ALPHABET CITY,6.0,2016-11-17 00:00:00,8000000,2A,2,6,8.0,1900.0,10009.0

In [4]:
# cast date columns to datetime type
mortgage15["DATE"] = pd.to_datetime(mortgage15["DATE"])
mortgage30["DATE"] = pd.to_datetime(mortgage30["DATE"])

In [5]:
# 
position = 0
date = datetime.datetime(2016,1,7)
for i in range(len(mortgage15)):
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage15.loc[position, "newValue"] = mortgage15.loc[i, "MORTGAGE15US"]
    mortgage15.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1

position = 0
date = datetime.datetime(2016,1,7)
for i in range(len(mortgage30)):
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    mortgage30.loc[position, "newValue"] = mortgage30.loc[i, "MORTGAGE30US"]
    mortgage30.loc[position, "newDate"] = date + datetime.timedelta(days = position)
    position += 1
    
mortgage15.set_index("newDate", inplace=True, drop=True)
mortgage30.set_index("newDate", inplace=True, drop=True)

In [6]:
sales["SALE DATE"] = pd.to_datetime(sales["SALE DATE"])
sales["SALE DATE"] = sales["SALE DATE"].dt.date

In [7]:
mortgage15.reset_index(inplace=True)
mortgage30.reset_index(inplace=True)

In [8]:
mortgage30["newDate"] = pd.to_datetime(mortgage30["newDate"])
mortgage30["newDate"] = mortgage30["newDate"].dt.date
mortgage15["newDate"] = pd.to_datetime(mortgage15["newDate"])
mortgage15["newDate"] = mortgage15["newDate"].dt.date

In [9]:
mortgage30.head()

      newDate       DATE  MORTGAGE30US  newValue
0  2016-01-07 2016-01-07          3.97      3.97
1  2016-01-08 2016-01-14          3.92      3.97
2  2016-01-09 2016-01-21          3.81      3.97
3  2016-01-10 2016-01-28          3.79      3.97
4  2016-01-11 2016-02-04          3.72      3.97

In [10]:
sales["SALE DATE"].loc[0]

datetime.date(2017, 7, 19)

In [11]:
mortgage30['newDate'].loc[1]

datetime.date(2016, 1, 8)

In [12]:
# merge sales data with mortgage data
sales = sales.merge(mortgage30[['newDate','newValue']],left_on='SALE DATE',right_on='newDate',how='left')
sales = sales.merge(mortgage15[['newDate','newValue']],left_on='SALE DATE',right_on='newDate',how='left')

In [14]:
sales.head()

,ADDRESS,APARTMENT NUMBER,BLOCK,BOROUGH,BUILDING CLASS AT PRESENT,BUILDING CLASS AT TIME OF SALE,BUILDING CLASS CATEGORY,COMMERCIAL UNITS,EASE-MENT,GROSS SQUARE FEET,LAND SQUARE FEET,LOT,NEIGHBORHOOD,RESIDENTIAL UNITS,SALE DATE,SALE PRICE,TAX CLASS AT PRESENT,TAX CLASS AT TIME OF SALE,TOTAL UNITS,Unnamed: 0,YEAR BUILT,ZIP CODE,newDate_x,newValue_x,newDate_y,newValue_y
0,153 AVENUE B,,392,1,C2,C2,07 RENTALS - WALKUP APARTMENTS,0.0,,6440,1633,6,ALPHABET CITY,5.0,2017-07-19,6625000,2A,2,5,4.0,1900.0,10009.0,2017-07-19,4.03,2017-07-19,3.29
1,234 EAST 4TH STREET,,399,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,3.0,,18690,4616,26,ALPHABET CITY,28.0,2016-12-14,-,2,2,31,5.0,1900.0,10009.0,2016-12-14,4.13,2016-12-14,3.36
2,197 EAST 3RD STREET,,399,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,1.0,,7803,2212,39,ALPHABET CITY,16.0,2016-12-09,-,2,2,17,6.0,1900.0,10009.0,2016-12-09,4.13,2016-12-09,3.36
3,154 EAST 7TH STREET,,402,1,C4,C4,07 RENTALS - WALKUP APARTMENTS,0.0,,6794,2272,21,ALPHABET CITY,10.0,2016-09-23,3936272,2B,2,10,7.0,1913.0,10009.0,2016-09-23,3.48,2016-09-23,2.76
4,301 EAST 10TH STREET,,404,1,C2,C2,07 RENTALS - WALKUP APARTMENTS,0.0,,4615,2369,55,ALPHABET CITY,6.0,2016-11-17,8000000,2A,2,6,8.0,1900.0,10009.0,2016-11-17,3.94,2016-11-17,3.14

In [15]:
# drop duplicate and unused columns
sales.drop("Unnamed: 0", inplace=True, axis=1)
sales.drop("EASE-MENT", inplace=True, axis=1)
sales.drop("APARTMENT NUMBER", inplace=True, axis=1)
sales.drop("newDate_x", inplace=True, axis=1)
sales.drop("newDate_y", inplace=True, axis=1)

In [16]:
sales.rename(columns= {"newValue_x":'30 Year Rate',"newValue_y":'15 Year Rate'},inplace=True)

In [17]:
# calculate age of property at time of sale
sales["SALE DATE"] = pd.to_datetime(sales["SALE DATE"])
age = (sales["SALE DATE"].dt.year - sales["YEAR BUILT"])
for i in range(len(age)):
    if age[i] > 2000:
        age[i] = np.nan

sales["AGE"] = age
sales.head(100)

,ADDRESS,BLOCK,BOROUGH,BUILDING CLASS AT PRESENT,BUILDING CLASS AT TIME OF SALE,BUILDING CLASS CATEGORY,COMMERCIAL UNITS,GROSS SQUARE FEET,LAND SQUARE FEET,LOT,NEIGHBORHOOD,RESIDENTIAL UNITS,SALE DATE,SALE PRICE,TAX CLASS AT PRESENT,TAX CLASS AT TIME OF SALE,TOTAL UNITS,YEAR BUILT,ZIP CODE,30 Year Rate,15 Year Rate,AGE
0,153 AVENUE B,392,1,C2,C2,07 RENTALS - WALKUP APARTMENTS,0.0,6440,1633,6,ALPHABET CITY,5.0,2017-07-19,6625000,2A,2,5,1900.0,10009.0,4.03,3.29,117.0
1,234 EAST 4TH STREET,399,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,3.0,18690,4616,26,ALPHABET CITY,28.0,2016-12-14,-,2,2,31,1900.0,10009.0,4.13,3.36,116.0
2,197 EAST 3RD STREET,399,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,1.0,7803,2212,39,ALPHABET CITY,16.0,2016-12-09,-,2,2,17,1900.0,10009.0,4.13,3.36,116.0
3,154 EAST 7TH STREET,402,1,C4,C4,07 RENTALS - WALKUP APARTMENTS,0.0,6794,2272,21,ALPHABET CITY,10.0,2016-09-23,3936272,2B,2,10,1913.0,10009.0,3.48,2.76,103.0
4,301 EAST 10TH STREET,404,1,C2,C2,07 RENTALS - WALKUP APARTMENTS,0.0,4615,2369,55,ALPHABET CITY,6.0,2016-11-17,8000000,2A,2,6,1900.0,10009.0,3.94,3.14,116.0
5,516 EAST 12TH STREET,405,1,C4,C4,07 RENTALS - WALKUP APARTMENTS,0.0,9730,2581,16,ALPHABET CITY,20.0,2017-07-20,-,2,2,20,1900.0,10009.0,3.96,3.23,117.0
6,210 AVENUE B,406,1,C4,C4,07 RENTALS - WALKUP APARTMENTS,0.0,4226,1750,32,ALPHABET CITY,8.0,2016-09-23,3192840,2B,2,8,1920.0,10009.0,3.48,2.76,96.0
7,520 EAST 14TH STREET,407,1,C7,C7,07 RENTALS - WALKUP APARTMENTS,2.0,21007,5163,18,ALPHABET CITY,44.0,2017-07-20,-,2,2,46,1900.0,10009.0,3.96,3.23,117.0
8,141 AVENUE D,379,1,D5,D5,08 RENTALS - ELEVATOR APARTMENTS,0.0,9198,1534,34,ALPHABET CITY,15.0,2017-06-20,-,2,2,15,1920.0,10009.0,3.91,3.18,97.0
9,629 EAST 5TH STREET,387,1,D9,D9,08 RENTALS - ELEVATOR APARTMENTS,0.0,18523,4489,153,ALPHABET CITY,24.0,2016-11-07,16232000,2,2,24,1920.0,10009.0,3.54,2.84,96.0
10,181 AVENUE C,394,1,D7,D7,08 RENTALS - ELEVATOR APARTMENTS,4.0,21328,4295,44,ALPHABET CITY,30.0,2017-07-20,-,2,2,34,1910.0,10009.0,3.96,3.23,107.0
11,530-532 EAST 5TH STREET,400,1,D1,D1,08 RENTALS - ELEVATOR APARTMENTS,0.0,12350,3717,21,ALPHABET CITY,10.0,2016-10-17,10350000,2B,2,10,2009.0,10009.0,3.47,2.76,7.0
12,"327 EAST 3 STREET, 1C",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,40,ALPHABET CITY,0.0,2016-09-06,1,2,2,0,1920.0,10009.0,3.46,2.77,96.0
13,"327 EAST 3 STREET, 1C",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,40,ALPHABET CITY,0.0,2017-03-10,499000,2,2,0,1920.0,10009.0,4.21,3.42,97.0
14,"327 EAST 3 STREET, 3A",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,40,ALPHABET CITY,0.0,2017-04-28,10,2,2,0,1920.0,10009.0,4.03,3.27,97.0
15,"327 EAST 3RD STREET, 5A",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,40,ALPHABET CITY,0.0,2017-06-09,529500,2,2,0,1920.0,10009.0,3.89,3.16,97.0
16,"327 EAST 3 STREET, 2E",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,40,ALPHABET CITY,0.0,2017-07-14,423000,2,2,0,1920.0,10009.0,4.03,3.29,97.0
17,"317 EAST 3RD STREET, 12",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,46,ALPHABET CITY,0.0,2017-03-16,501000,2,2,0,1925.0,10009.0,4.30,3.50,92.0
18,"311 EAST 3RD STREET, 17",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,49,ALPHABET CITY,0.0,2016-09-01,450000,2,2,0,1920.0,10009.0,3.46,2.77,96.0
19,"311 EAST 3RD, 22",373,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,49,ALPHABET CITY,0.0,2017-08-17,510000,2,2,0,1920.0,10009.0,3.89,3.16,97.0
20,"702 EAST 5TH STREET, 5E",374,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,8,ALPHABET CITY,0.0,2016-09-07,-,2C,2,0,1900.0,10009.0,3.46,2.77,116.0
21,"742 EAST 6TH STREET, 1",375,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,30,ALPHABET CITY,0.0,2017-08-30,350000,2,2,0,1902.0,10009.0,3.86,3.16,115.0
22,244 EAST 7TH STREET,376,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,16776,4131,14,ALPHABET CITY,24.0,2017-06-21,11900000,2,2,24,1928.0,10009.0,3.91,3.18,89.0
23,244 EAST 7TH STREET,376,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,14,ALPHABET CITY,0.0,2017-06-21,11900000,2,2,0,1928.0,10009.0,3.91,3.18,89.0
24,"248 EAST 7TH STREET, 24",376,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,16,ALPHABET CITY,0.0,2017-01-30,350000,2,2,0,1928.0,10009.0,4.19,3.40,89.0
25,"248 EAST 7TH STREET, 2",376,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,16,ALPHABET CITY,0.0,2017-07-07,404000,2,2,0,1928.0,10009.0,3.96,3.22,89.0
26,"254 EAST 7TH STREET, 4",376,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,19,ALPHABET CITY,0.0,2017-06-21,535000,2,2,0,1910.0,10009.0,3.91,3.18,107.0
27,"267 EAST 7 ST, 4",377,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,54,ALPHABET CITY,0.0,2017-08-04,1400000,2C,2,0,1920.0,10009.0,3.93,3.18,97.0
28,"255 EAST 7TH STREET, 3F",377,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,60,ALPHABET CITY,0.0,2017-01-09,866000,2C,2,0,1900.0,10009.0,4.20,3.44,117.0
29,"414 EAST 10TH STREET, 4E",379,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,15,ALPHABET CITY,0.0,2017-04-18,355000,2,2,0,1930.0,10009.0,4.08,3.34,87.0
30,"414 EAST 10TH STREET, 1C",379,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,15,ALPHABET CITY,0.0,2017-06-19,-,2,2,0,1930.0,10009.0,3.91,3.18,87.0
31,"206 EAST 7TH STREET, 17,18",389,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,21,ALPHABET CITY,0.0,2017-08-28,805000,2,2,0,1900.0,10009.0,3.86,3.16,117.0
32,"623 EAST 6TH STREET, 8",389,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,49,ALPHABET CITY,0.0,2017-05-10,475000,2C,2,0,1910.0,10009.0,4.02,3.27,107.0
33,"621 EAST 6TH STREET, 6",389,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,50,ALPHABET CITY,0.0,2016-12-02,450000,2C,2,0,1920.0,10009.0,4.08,3.34,96.0
34,"621 EAST 6TH STREET, 10",389,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,50,ALPHABET CITY,0.0,2017-01-31,450000,2C,2,0,1920.0,10009.0,4.19,3.40,97.0
35,"199 EAST 7TH STREET, 2C",390,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,55,ALPHABET CITY,0.0,2017-06-28,810000,2,2,0,1935.0,10009.0,3.90,3.17,82.0
36,"616 EAST 9TH STREET, 4W",391,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,14,ALPHABET CITY,0.0,2016-12-07,-,2,2,0,1910.0,10009.0,4.08,3.34,106.0
37,"618 EAST 9TH STREET, 2 E",391,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,14,ALPHABET CITY,0.0,2017-08-24,300000,2,2,0,1910.0,10009.0,3.86,3.16,107.0
38,"620 EAST 9TH STREET, 3E",391,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,14,ALPHABET CITY,0.0,2017-08-30,300000,2,2,0,1910.0,10009.0,3.86,3.16,107.0
39,"323 EAST 8TH STREET, 2A",391,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,48,ALPHABET CITY,0.0,2017-06-27,579000,2,2,0,1910.0,10009.0,3.90,3.17,107.0
40,"303 EAST 8TH STREET, 3F",391,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,57,ALPHABET CITY,0.0,2017-03-17,1500000,2,2,0,1900.0,10009.0,4.30,3.50,117.0
41,"163 AVENUE C, 2",393,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,39,ALPHABET CITY,0.0,2017-06-14,25000,2C,2,0,1900.0,10009.0,3.89,3.16,117.0
42,"633 EAST 11TH STREET, 12",394,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,52,ALPHABET CITY,0.0,2017-01-17,512000,2,2,0,1937.0,10009.0,4.12,3.37,80.0
43,"633 EAST 11TH STREET, 23",394,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,52,ALPHABET CITY,0.0,2017-01-11,410000,2,2,0,1937.0,10009.0,4.20,3.44,80.0
44,"633 EAST 11TH STREET, 19",394,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,52,ALPHABET CITY,0.0,2017-04-21,500000,2,2,0,1937.0,10009.0,3.97,3.23,80.0
45,"633 E 11TH ST, 17",394,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,52,ALPHABET CITY,0.0,2017-06-29,510000,2,2,0,1937.0,10009.0,3.88,3.17,80.0
46,"634 EAST 14TH STREET, 1",396,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,20,ALPHABET CITY,0.0,2016-10-05,475000,2,2,0,1920.0,10009.0,3.42,2.72,96.0
47,"634 EAST 14TH STREET, 4",396,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,20,ALPHABET CITY,0.0,2017-02-02,789019,2,2,0,1920.0,10009.0,4.19,3.41,97.0
48,"626 EAST 14TH STREET, 5",396,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,20,ALPHABET CITY,0.0,2017-03-20,-,2,2,0,1920.0,10009.0,4.30,3.50,97.0
49,"632 EAST 14TH STREET, 15",396,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,20,ALPHABET CITY,0.0,2017-03-20,-,2,2,0,1920.0,10009.0,4.30,3.50,97.0
50,"632 EAST 14TH STREET, 3",396,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,20,ALPHABET CITY,0.0,2017-04-13,425000,2,2,0,1920.0,10009.0,4.08,3.34,97.0
51,"626 EAST 14TH STREET, 9",396,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,20,ALPHABET CITY,0.0,2017-06-29,490000,2,2,0,1920.0,10009.0,3.88,3.17,97.0
52,"185 EAST 2ND STREET, C",397,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,25,ALPHABET CITY,0.0,2017-06-06,409000,2,2,0,1915.0,10009.0,3.94,3.19,102.0
53,"185 EAST 2ND STREET, 2B",397,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,25,ALPHABET CITY,0.0,2017-07-17,415000,2,2,0,1915.0,10009.0,4.03,3.29,102.0
54,"162 EAST 2ND STREET, 3A",398,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,58,ALPHABET CITY,0.0,2016-12-06,420000,2,2,0,1950.0,10009.0,4.08,3.34,66.0
55,"162 EAST 2ND STREET, 1C",398,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,58,ALPHABET CITY,0.0,2017-07-13,435000,2,2,0,1950.0,10009.0,4.03,3.29,67.0
56,"225 EAST 4TH STREET, 1",400,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,45,ALPHABET CITY,0.0,2017-05-17,575000,2,2,0,1937.0,10009.0,4.05,3.29,80.0
57,"225 EAST 4TH STREET, 20",400,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,45,ALPHABET CITY,0.0,2017-08-28,605000,2,2,0,1937.0,10009.0,3.86,3.16,80.0
58,"504 EAST 6TH STREET, 1",401,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,12,ALPHABET CITY,0.0,2017-05-31,799000,2C,2,0,1900.0,10009.0,3.95,3.19,117.0
59,"504 EAST 6TH STREET, 5",401,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,12,ALPHABET CITY,0.0,2017-07-12,800000,2C,2,0,1900.0,10009.0,3.96,3.22,117.0
60,"527 EAST 5 STREET, 1",401,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,50,ALPHABET CITY,0.0,2017-01-19,54993,2C,2,0,1900.0,10009.0,4.09,3.34,117.0
61,"513 EAST 5TH STREET, 3A",401,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,57,ALPHABET CITY,0.0,2016-12-14,410000,2,2,0,1929.0,10009.0,4.13,3.36,87.0
62,"537 EAST 6TH STREET, 5",402,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,47,ALPHABET CITY,0.0,2017-05-03,1475000,2C,2,0,1900.0,10009.0,4.03,3.27,117.0
63,"512 EAST 11TH STREET, 5C",404,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,10,ALPHABET CITY,0.0,2016-09-29,335000,2,2,0,1929.0,10009.0,3.42,2.72,87.0
64,"534 EAST 11TH STREET, 21",404,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,21,ALPHABET CITY,0.0,2017-08-07,490000,2,2,0,1920.0,10009.0,3.93,3.18,97.0
65,"544 EAST 11TH STREET, 3A",404,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,26,ALPHABET CITY,0.0,2017-01-20,750000,2C,2,0,1928.0,10009.0,4.09,3.34,89.0
66,"546 EAST 11TH STREET, 2B",404,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,27,ALPHABET CITY,0.0,2017-02-23,780000,2C,2,0,1900.0,10009.0,4.16,3.37,117.0
67,"297 EAST 10TH STREET, 2",404,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,57,ALPHABET CITY,0.0,2016-09-12,2400000,2C,2,0,1925.0,10009.0,3.44,2.76,91.0
68,"519 EAST 11TH STREET, 4W",405,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,51,ALPHABET CITY,0.0,2017-08-09,380000,2,2,0,1910.0,10009.0,3.93,3.18,107.0
69,"527 EAST 12TH STREET, E2",406,1,C6,C6,09 COOPS - WALKUP APARTMENTS,0.0,-,-,50,ALPHABET CITY,0.0,2017-04-07,430000,2,2,0,1901.0,10009.0,4.10,3.36,116.0
70,"735 EAST 9 STREET, 3RW",379,1,D0,D0,10 COOPS - ELEVATOR APARTMENTS,0.0,-,-,45,ALPHABET CITY,0.0,2017-04-13,499900,2,2,0,1920.0,10009.0,4.08,3.34,97.0
71,"300 EAST 4TH STREET, 1D",386,1,D0,D0,10 COOPS - ELEVATOR APARTMENTS,0.0,-,-,36,ALPHABET CITY,0.0,2017-05-11,1400000,2,2,0,1940.0,10009.0,4.05,3.29,77.0
72,"223 EAST 3RD STREET, 2D",386,1,D4,D4,10 COOPS - ELEVATOR APARTMENTS,0.0,-,-,58,ALPHABET CITY,0.0,2016-09-29,694000,2,2,0,1900.0,10009.0,3.42,2.72,116.0
73,254 EAST 2ND STREET,385,1,RR,RR,11A CONDO-RENTALS,0.0,36472,-,1102,ALPHABET CITY,47.0,2016-10-13,28000000,2,2,47,2005.0,10009.0,3.47,2.76,11.0
74,183-189 AVENUE B,394,1,,RR,11A CONDO-RENTALS,0.0,-,-,1602,ALPHABET CITY,0.0,2017-08-09,8058923,,2,0,0.0,0.0,3.93,3.18,NaN
75,250 EAST HOUSTON STREET,397,1,RR,RR,11A CONDO-RENTALS,0.0,-,33650,1301,ALPHABET CITY,132.0,2016-10-19,52625000,2,2,132,1989.0,10002.0,3.47,2.76,27.0
76,211 EAST 3RD STREET,386,1,R2,R2,12 CONDOS - WALKUP APARTMENTS,0.0,-,-,1002,ALPHABET CITY,1.0,2016-12-30,620000,2,2,1,0.0,10009.0,4.32,3.55,NaN
77,182 EAST 2ND STREET,398,1,R2,R2,12 CONDOS - WALKUP APARTMENTS,0.0,-,-,1039,ALPHABET CITY,1.0,2017-02-24,-,2,2,1,0.0,10009.0,4.16,3.37,NaN
78,511 EAST 11TH STREET,405,1,R2,R2,12 CONDOS - WALKUP APARTMENTS,0.0,-,-,1211,ALPHABET CITY,1.0,2017-07-20,-,2,2,1,0.0,10009.0,3.96,3.23,NaN
79,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1003,ALPHABET CITY,1.0,2016-09-21,762669,2,2,1,1920.0,10009.0,3.50,2.77,96.0
80,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1004,ALPHABET CITY,1.0,2016-09-12,772851,2,2,1,1920.0,10009.0,3.44,2.76,96.0
81,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1005,ALPHABET CITY,1.0,2016-11-03,1034880,2,2,1,1920.0,10009.0,3.54,2.84,96.0
82,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1006,ALPHABET CITY,1.0,2016-11-03,-,2,2,1,1920.0,10009.0,3.54,2.84,96.0
83,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1007,ALPHABET CITY,1.0,2016-11-03,-,2,2,1,1920.0,10009.0,3.54,2.84,96.0
84,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1008,ALPHABET CITY,1.0,2016-11-03,-,2,2,1,1920.0,10009.0,3.54,2.84,96.0
85,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1009,ALPHABET CITY,1.0,2016-09-07,800000,2,2,1,1920.0,10009.0,3.46,2.77,96.0
86,324 EAST 4TH STREET,373,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1011,ALPHABET CITY,1.0,2016-09-01,2295759,2,2,1,1920.0,10009.0,3.46,2.77,96.0
87,754 EAST 6TH STREET,375,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1004,ALPHABET CITY,1.0,2017-03-31,875000,2,2,1,0.0,10009.0,4.14,3.39,NaN
88,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1001,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
89,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1002,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
90,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1003,ALPHABET CITY,1.0,2017-07-14,-,2,2,1,2014.0,10009.0,4.03,3.29,3.0
91,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1004,ALPHABET CITY,1.0,2017-07-14,-,2,2,1,2014.0,10009.0,4.03,3.29,3.0
92,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1005,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
93,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1006,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
94,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1007,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
95,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1008,ALPHABET CITY,1.0,2017-02-14,701341,2,2,1,2014.0,10009.0,4.17,3.39,3.0
96,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1009,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
97,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1010,ALPHABET CITY,1.0,2017-07-14,-,2,2,1,2014.0,10009.0,4.03,3.29,3.0
98,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1011,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0
99,399 EAST 8TH STREET,378,1,R4,R4,13 CONDOS - ELEVATOR APARTMENTS,0.0,-,-,1012,ALPHABET CITY,1.0,2017-05-25,-,2,2,1,2014.0,10009.0,3.95,3.19,3.0

In [18]:
sales.columns

Index(['ADDRESS', 'BLOCK', 'BOROUGH', 'BUILDING CLASS AT PRESENT',
       'BUILDING CLASS AT TIME OF SALE', 'BUILDING CLASS CATEGORY',
       'COMMERCIAL UNITS', 'GROSS SQUARE FEET', 'LAND SQUARE FEET', 'LOT',
       'NEIGHBORHOOD', 'RESIDENTIAL UNITS', 'SALE DATE', 'SALE PRICE',
       'TAX CLASS AT PRESENT', 'TAX CLASS AT TIME OF SALE', 'TOTAL UNITS',
       'YEAR BUILT', 'ZIP CODE', '30 Year Rate', '15 Year Rate', 'AGE'],
      dtype='object')

In [19]:
sales.shape

(166968, 22)

In [20]:
# output clean dataset
sales.to_csv('cleaned_allyears.csv',index=False)